apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploynew
  labels:
    app: autodeploynew
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718793124577
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploynew
  template:
    metadata:
      labels:
        app: autodeploynew
    spec:
      containers:
        - name: autodeploynew
          image: acrworkflow1718793124577.azurecr.io/image-workflow-1718793124577:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
