apiVersion: v1
kind: Service
metadata:
  name: autodeploynew
  namespace: namespace-workflow-1718793124577
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploynew
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000